import '../styles/globals.css'
import Navbar from '../components/Layout/Navbar'
import Footer from '../components/Layout/Footer'
import { useRouter } from 'next/router'
import GoTop from "../components/Layout/GoTop"
import Head from 'next/head'

export default function App({ Component, pageProps }) {

  const router = useRouter()

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Navbar />
      <Component {...pageProps} />
      <div className={`wrapper ${router.pathname === '/' ? '-mt-20 lg:mt-[-18rem]' : ''}  z-30 relative`}>
        <Footer />
      </div>
      <GoTop />
    </>
  )
}
